### ISSUE TITLE
How does this relate to wp-background-processing?

### ISSUE THREAD

**Issue by jonathanstegall** [A5hleyRich/wp-queue#1]
I'm just curious how these two things relate to one another (if at all)? Does wp-queue replace wp-background-processing (even if just for some uses)? When do/do not their functionalities overlap?

**Comment by A5hleyRich** [comment]
wp-queue introduces a fully fledged queuing system into WordPress with the following features (some still WIP):

- [x] Delayed jobs
- [x] Handling of job failures, with automatic retries
- [x] Job failures are saved and can be attempted again manually
- [ ] Multiple queue connections, allowing jobs to be saved to memory instead of the database
- [ ] Fire up additional workers via the CLI for faster job processing

Both libraries have their place, hence the separate repos. wp-background-processing is more suited to pushing the occasional task to a background process. If you're dealing with thousands of jobs then wp-queue is the library to use because it won't flood the wp_options table.
